// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.26.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// The type `GenieCode` is not used by any `pub` functions, thus it is ignored.

enum FourPlayer {
  disabled,
  fourScore,
  satellite,
}

enum NesRegion {
  ntsc,
  pal,
  dendy,
}

enum Player {
  one,
  two,
  three,
  four,
}

enum RamState {
  allZeros,
  allOnes,
  random,
}

enum VideoFilter {
  pixellate,
  ntsc,
}
