// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.26.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::rust_async::RwLock<NesTexture>>
@sealed
class NesTexture extends RustOpaque {
  NesTexture.dcoDecode(List<dynamic> wire)
      : super.dcoDecode(wire, _kStaticData);

  NesTexture.sseDecode(int ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_NesTexture,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_NesTexture,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_NesTexturePtr,
  );

  static Future<NesTexture?> create({required int handle, dynamic hint}) =>
      RustLib.instance.api.nesTextureCreate(handle: handle, hint: hint);

  int id({dynamic hint}) => RustLib.instance.api.nesTextureId(
        that: this,
      );

  Future<void> render({required List<int> data, dynamic hint}) =>
      RustLib.instance.api.nesTextureRender(
        that: this,
        data: data,
      );
}
