[package]
name = "flutter_nes"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0-dev.26"
irondash_texture = "0.5.0"
irondash_run_loop = "0.5.0"
crossbeam-channel = "0.5.12"
nes_core = {path = "../nes_core"}
rgb = "0.8.37"
anyhow = "1.0.80"
