[package]
name = "nes_core"
version = "0.1.0"
license = "MIT"
description = "A NES emulator written in Rust. "
edition = "2021"
repository = "https://github.com/Kylin3216/retro_game_box.git"
homepage = "https://github.com/Kylin3216/retro_game_box.git"
keywords = ["nes"]

[[test]]
name = "test_rom"
path = "test/rom.rs"

[dependencies]
enum_dispatch = "0.3.12"
log = "0.4.21"
lazy_static = { version = "1.4.0" }
rand = { version = "0.8.5", default-features = false, features = ["small_rng"] }
bitflags = { version = "2.4.2", features = ["serde"] }
serde = { version = "1.0.197", default-features = false, features = ["derive", "alloc"] }

[dev-dependencies]
image = "0.24.9"
serde_json = "1.0.109"
